wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.7
    session_history: code/_session_history.ipynb
    start_time: 1628703267
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.7.7
      5: 0.12.0
      8:
      - 1
      - 5
